FROM golang:alpine

LABEL app="build-admintest"
LABEL REPO="https://github.com/jimbydamonk/admintest"

ENV GOROOT=/usr/lib/go \
    GOPATH=/gopath \
    GOBIN=/gopath/bin \
    PROJPATH=/gopath/src/github.com/jimbydamonk/admintest

# Because of https://github.com/docker/docker/issues/14914
ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin

WORKDIR /gopath/src/github.com/jimbydamonk/admintest

CMD ["make","build-static"]